# ============================================
# SUPABASE-NATIVE REAL ESTATE INTELLIGENCE SYSTEM
# Terraform Configuration — Main
# ============================================

terraform {
  required_version = ">= 1.5.0"

  required_providers {
    postgresql = {
      source  = "cyrilgdn/postgresql"
      version = "~> 1.25"
    }
    null = {
      source  = "hashicorp/null"
      version = "~> 3.2"
    }
    local = {
      source  = "hashicorp/local"
      version = "~> 2.5"
    }
  }

  backend "local" {
    path = "terraform.tfstate"
  }
}

# ============================================
# Provider Configuration
# ============================================

# Supabase project managed via dashboard
# PostgreSQL provider handles DB-level operations directly

provider "postgresql" {
  host            = var.supabase_db_host
  port            = var.supabase_db_port
  database        = var.supabase_db_name
  username        = var.supabase_db_user
  password        = var.supabase_db_password
  sslmode         = "require"
  connect_timeout = 15
  superuser       = false
}

# ============================================
# Supabase Project Reference
# Project is managed externally via Supabase Dashboard.
# Connection details provided through variables.
# Project ref: var.supabase_project_ref
# ============================================

# ============================================
# PostgreSQL Extensions
# ============================================

resource "postgresql_extension" "vector" {
  name     = "vector"
  database = var.supabase_db_name
  schema   = "public"
}

resource "postgresql_extension" "postgis" {
  name     = "postgis"
  database = var.supabase_db_name
  schema   = "extensions"
}

resource "postgresql_extension" "pg_trgm" {
  name     = "pg_trgm"
  database = var.supabase_db_name
  schema   = "public"
}

resource "postgresql_extension" "btree_gin" {
  name     = "btree_gin"
  database = var.supabase_db_name
  schema   = "public"
}

resource "postgresql_extension" "uuid_ossp" {
  name     = "uuid-ossp"
  database = var.supabase_db_name
  schema   = "extensions"
}

# ============================================
# Database Configuration via SQL
# ============================================

resource "null_resource" "db_config" {
  depends_on = [
    postgresql_extension.vector,
    postgresql_extension.postgis,
    postgresql_extension.pg_trgm,
    postgresql_extension.btree_gin
  ]

  provisioner "local-exec" {
    command     = "$env:DATABASE_URL='postgresql://${var.supabase_db_user}:${var.supabase_db_password}@${var.supabase_db_host}:${var.supabase_db_port}/${var.supabase_db_name}'; & '${path.module}/../venv/Scripts/python.exe' '${path.module}/configure_db.py'"
    interpreter = ["powershell", "-Command"]
  }

  triggers = {
    always_run = timestamp()
  }
}

# ============================================
# Environment Configuration Output
# ============================================

resource "local_file" "env_config" {
  filename = "${path.module}/../backend/.env.infrastructure"
  content  = <<-EOT
    # Auto-generated by Terraform — DO NOT EDIT MANUALLY
    # Generated: ${timestamp()}

    # PostgreSQL (Supabase)
    DATABASE_URL=postgresql+asyncpg://${var.supabase_db_user}:${var.supabase_db_password}@${var.supabase_db_host}:${var.supabase_db_port}/${var.supabase_db_name}
    DATABASE_URL_SYNC=postgresql://${var.supabase_db_user}:${var.supabase_db_password}@${var.supabase_db_host}:${var.supabase_db_port}/${var.supabase_db_name}

    # Supabase
    SUPABASE_URL=${var.supabase_url}
    SUPABASE_ANON_KEY=${var.supabase_anon_key}
    SUPABASE_SERVICE_ROLE_KEY=${var.supabase_service_role_key}
    SUPABASE_PROJECT_REF=${var.supabase_project_ref}

    # Extensions
    PGVECTOR_ENABLED=true
    POSTGIS_ENABLED=true
    HNSW_ITERATIVE_SCAN=relaxed_order

    # Groq
    GROQ_API_KEY=${var.groq_api_key}
    GROQ_MODEL=${var.groq_model}
    GROQ_MAX_CONCURRENT=${var.groq_max_concurrent}

    # Application
    APP_ENV=${var.environment}
    DEBUG=${var.debug}
    LOG_LEVEL=${var.log_level}
  EOT
}

# ============================================
# Outputs JSON
# ============================================

resource "local_file" "outputs_json" {
  filename = "${path.module}/outputs.json"
  content  = jsonencode({
    project_ref      = var.supabase_project_ref
    supabase_url     = var.supabase_url
    db_host          = var.supabase_db_host
    db_port          = var.supabase_db_port
    db_name          = var.supabase_db_name
    extensions       = {
      pgvector  = "enabled"
      postgis   = "enabled"
      pg_trgm   = "enabled"
      btree_gin = "enabled"
      uuid_ossp = "enabled"
    }
    hnsw_config      = "iterative_scan=relaxed_order"
    environment      = var.environment
    timestamp        = timestamp()
  })
}
